import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Fredoka } from "@next/font/google";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${fredoka.className} antialiased animate-in fade-in-0 duration-1000 h-screen flex flex-col justify-between`}
      >
        <div>
        <Navbar />
        {children}
        </div>
       
        <Footer />
        <Toaster richColors position="top-center"/>
      </body>
    </html>
  );
}
